#!/bin/bash

compositor_PID=$(pidof picom)

while [ ! -z "$compositor_PID" ]; do
  kill $compositor_PID
  sleep .1
  compositor_PID=$(pidof picom)
done

/usr/bin/picom --config "$HOME/.config/picom/config" --experimental-backends
